sudo: required
dist: trusty
language: bash

stages:
  - name: Python test
  - name: Copy artifact
    if: branch = master
  - name: Terraform run
    if: branch = master
services:
  - docker
env:
  - TF_INPUT=false # No interraction

install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get -qq update
  - sudo apt-get -t trusty-backports install shellcheck
  - sudo pip install awscli  
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.5/terraform_0.12.5_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

jobs:
  include:

    - stage: Python test
      script:
        - echo "Check for commit ${TRAVIS_COMMIT} and tag ${TRAVIS_TAG} from branch ${TRAVIS_BRANCH}."
        - echo "This is build number ${TRAVIS_BUILD_NUMBER}, for ${TRAVIS_REPO_SLUG}."
        - mkdir /tmp/config-custom
        - docker pull almerhor/pylint:default
        - docker run --rm -v $(pwd):/pylint -v $(pwd)/test:/tmp/config-custom almerhor/pylint:default py/cloud_control_state_action_ec2.py requirements-custom.txt
    
    - stage: Copy artifact
      language: python
      script:
        - zip cloud_control_state_action_ec2.zip py/cloud_control_state_action_ec2.py
        - aws s3 cp cloud_control_state_action_ec2.zip s3://${artifact_bucket}/${TRAVIS_REPO_SLUG}/$(date +%s)-${TRAVIS_COMMIT}-cloud_control_state_action_ec2.zip

    - stage: Terraform run
      script:
        - cd provision
        - echo "Feeding terraform.tf with variables."
        - sed -i -e "s/STATEBUCKETNAME/${terraform_bucket}/g" terraform.tf_template
        - sed -i -e "s/TABLENAME/${terraform_table}/g" terraform.tf_template
        - sed -i -e "s/REGION/${terraform_region}/g" terraform.tf_template
        - mv terraform.tf_template terraform.tf
        - echo "Feeding terraform.tfvars with variables."
        - sed -i -e "s/REGION/${terraform_region}/g" terraform.tfvars_template
        - sed -i -e "s/TABLENAME/${terraform_table}/g" terraform.tfvars_template
        - sed -i -e "s/STATEBUCKETNAME/${terraform_bucket}/g" terraform.tfvars_template
        - sed -i -e "s/ARTIFACTBUCKETNAME/${artifact_bucket}/g" terraform.tfvars_template
        - sed -i -e "s/ENVIRONMENT/${terraform_environment}/g" terraform.tfvars_template
        - mv terraform.tfvars_template terraform.tfvars
        - echo "Feeding main.tf with variables."
        - sed -i -e "s/ACCOUNTNUMBER/${account_number}/g" main.tf
        - sed -i -e "s/ARTIFACTBUCKETNAME/${artifact_bucket}/g" main.tf
        - terraform init
        - terraform validate
        - ./execute.sh

        